# 雪花ID配置
snow:
  work-id: 3
  data-center-id: 1

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msd-user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&generateSimpleParameterMetadata=true&autoReconnect=true&useSSL=true
    username: root
    password: Admin888
    druid:
      #连接池的最大数据库连接数。设为0表示无限制
      max-active: 20
      #初始化数量
      initial-size: 2
      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
      max-wait: 60000
      #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接
      min-idle: 2

seata:
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group  # 客户端事务组名
  service:
    vgroupMapping:
      default_tx_group: default      # 映射到服务端集群名
  registry:
    type: nacos                 # 注册中心类型（nacos/eureka等）
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 69dba6d6-2196-4612-a295-1e9dc516bde9
      group: DEFAULT_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      data-id: seataServer.properties
      namespace: 69dba6d6-2196-4612-a295-1e9dc516bde9