server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin888
    url: jdbc:mysql://127.0.0.1:3306/security02?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml
  typeAliasesPackage: org.monkey.msd.security.domain
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/demo
#    username: root
#    password: Admin888
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10000
#    password:
#    lettuce:
#      pool:
#        #最大连接数据库连接数,设 0 为没有限制
#        max-active: 8
#        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        max-wait: 1000
#        #最大等待连接中的数量,设 0 为没有限制
#        max-idle: 500
#        #最小等待连接中的数量,设 0 为没有限制
#
#
#logging:
#  file:
#    path: /www/spring-boot-demo/logs