server:
  port: 8080

spring:
  application:
    name: tracing-gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**

        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**


logging:
  file:
    path: /monkey/tracing/logs

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      # 采样率的概率，100%采样
      probability: 1.0